### ISSUE TITLE
Track blocked russh 0.46 → 0.60 upgrade (GHSA-f5v4-2wr6-hqmg DoS) — pre-release pkcs8/ed25519-dalek conflict

### ISSUE THREAD

**Issue by Dicklesworthstone** [Dicklesworthstone/charmed_rust#44]
## Summary

Tracking the blocked upgrade of `russh` from 0.46.0 (current) to 0.60.1 (latest) and `russh-keys` from 0.46.0 to 0.49.2. Includes a security advisory we should ship as soon as the upgrade unblocks.

## Why the upgrade matters

**Security fix (real exposure):** [GHSA-f5v4-2wr6-hqmg](https://github.com/Eugeny/russh/security/advisories/GHSA-f5v4-2wr6-hqmg) — DoS vulnerability in russh's keyboard-interactive auth path. An unauthenticated client can trigger a multi-GB allocation likely killing the process under OOM.

`charmed-wish` exposes `KeyboardInteractive` in its `MethodSet`, so any wish server with that method enabled is exposed under the current pinned russh 0.46.

Other notable changes through 0.46 → 0.60:
- 0.49: `client::Handle::authenticate_publickey` now takes `PrivateKeyWithHashAlg` (RSA hash-algorithm fix)
- 0.58: ~21% throughput improvement (mlock removal); CryptoVec → `impl Into<Bytes>` on a few public APIs; `SshId::Standard` now `Cow<'static, str>` instead of `String`
- 0.59: certificate-based auth via SSH agent; replaces libcrux-ml-kem with RustCrypto ml-kem; aws-lc-rs bumped to fix RUSTSEC-2026-0044/0048
- 0.60: rand 0.10

## What blocks the upgrade today

**Pre-release version chaos in the RustCrypto ecosystem** that russh transitively pulls in. Reproduced on 2026-04-28:

1. `russh = "0.60"` resolves `internal-russh-forked-ssh-key 0.6.18`, which depends on `ed25519-dalek = "=3.0.0-pre.6"` (exact pin).
2. `ed25519-dalek 3.0.0-pre.6` was authored against `pkcs8 0.11.0-rc.10` and uses `pkcs8::Error::KeyMalformed` as a unit variant.
3. The published `pkcs8 0.11.0` (and `0.11.0-rc.11+`) changed `KeyMalformed` to a tuple variant `KeyMalformed(KeyError)`.
4. `russh 0.60.1`'s direct dep `pkcs8 = "^0.11.0-rc.11"` forces the resolver onto the new pkcs8 API.
5. Result: `ed25519-dalek-3.0.0-pre.6` no longer compiles. Same failure shape under russh 0.59 (pulls `rsa = "0.10.0-rc.12"` which has the same outdated `KeyMalformed` usage in `rsa::pkcs1v15::sign`).
6. Pinning `pkcs8` lower than `0.11.0-rc.11` is rejected because russh's direct constraint excludes it.

Reproduction:
```
russh = { version = "0.60", features = ["async-trait"] }
russh-keys = "0.49"
cargo check -p charmed-wish
# error[E0277]: `?` couldn't convert the error to `ed25519::pkcs8::Error`
# error[E0308]: mismatched types — pkcs8::Error::KeyMalformed expected (Error), found enum constructor
# error: could not compile `ed25519-dalek` (lib) due to 2 previous errors
```

(Same fingerprint with 0.58 / 0.59 — the constraint chain that breaks is the same.)

## Migration scope on our side once the upstream ecosystem settles

These are the exact code changes we'll need in `crates/wish/src/{lib,handler}.rs` once the upstream resolver works again:

- `russh_keys::key::PublicKey` → `russh_keys::PublicKey` (re-export of `ssh_key::PublicKey`)
- `russh_keys::key::KeyPair` → `russh_keys::PrivateKey` (server `Config::keys` is now `Vec<PrivateKey>`, no `try_from(&private_key)` needed)
- `KeyPair::generate_ed25519()` → `ssh_key::PrivateKey::random(&mut russh_keys::key::safe_rng(), ssh_key::Algorithm::Ed25519)?`
- `key.name()` → `key.algorithm().as_str()`
- `key.public_key_bytes()` → `key.to_bytes()?`
- `russh::SshId::Standard(self.options.version.clone())` → `SshId::Standard(self.options.version.clone().into())` (Cow wrap)
- `russh = "0.60"` needs `features = ["async-trait"]` to keep our `#[async_trait]` `Handler` impl working without rewriting every method as native AFIT.

## Action

- **Now**: Add a README warning that `MethodSet::KEYBOARD_INTERACTIVE` shouldn't be enabled in production until russh is upgraded past the GHSA-f5v4-2wr6-hqmg fix.
- **Watch**: Reopen this issue when either (a) `ed25519-dalek` ships `3.0.0-pre.7+` against the released pkcs8, (b) russh ships a release that doesn't pin pre-release crypto crates exclusively, or (c) `internal-russh-forked-ssh-key` releases a 0.7.x against stable RustCrypto.
- **Manual probe**: rerunning `cargo update; cargo check -p charmed-wish` with `russh = "0.60"` periodically is enough to know when the path opens.

## Related

- Closed Dependabot PR #43 (the cargo-group bump that surfaced this).
- ed25519-dalek pkcs8 incompat: https://github.com/dalek-cryptography/curve25519-dalek/issues — track upstream for 3.0.0-pre.7+
- russh: https://github.com/Eugeny/russh/issues — track for stable RustCrypto release line

**Comment by Dicklesworthstone** [comment]
README warning landed in [`83acf8e`](https://github.com/Dicklesworthstone/charmed_rust/commit/83acf8e) (workspace README + crates/wish README). The notice covers GHSA-f5v4-2wr6-hqmg, names the affected `MethodSet::KEYBOARD_INTERACTIVE` / `with_keyboard_interactive_auth(...)` surface, and directs users to password / public-key auth as the temporary mitigation, with this issue linked for upgrade tracking.

Leaving the issue open as the upstream RustCrypto pre-release (pkcs8 / ed25519-dalek) chain is the actual blocker. Periodic `cargo update; cargo check -p charmed-wish` against `russh = "0.60"` is the right probe.

**Comment by Dicklesworthstone** [comment]
**Status update 2026-04-30: upstream blocker cleared.**

Probed at HEAD with:

```toml
russh = { version = "0.60", features = ["async-trait"] }
russh-keys = "0.49"
```

`cargo check -p charmed-wish` now resolves the dependency graph and compiles past the `pkcs8::Error::KeyMalformed` shape conflict that previously broke `ed25519-dalek-3.0.0-pre.6`. The pre-release ecosystem has settled — `russh 0.60.1` no longer pulls a `pkcs8` constraint that excludes the version `ed25519-dalek-3.0.0-pre.6` requires.

**Remaining work is the migration itself** — 44 compile errors, all in `crates/wish/src/lib.rs` and matching the scope already documented above, plus these additional API surfaces not in the original list:

- `MethodSet::PASSWORD`, `MethodSet::KEYBOARD_INTERACTIVE`, `MethodSet::NONE` are no longer associated constants on `MethodSet` in 0.60. Need to find the new constructor (likely `MethodKind` variants in 0.59+ flowing into `MethodSet`).
- `russh::server::Config::auth_banner` field is removed; available fields per rustc are `server_id`, `methods`, `auth_rejection_time`, `auth_rejection_time_initial`, `keys` and 11 others. Need to check whether banner moved to a `Handler` callback.

The DoS advisory (GHSA-f5v4-2wr6-hqmg) is fixable now whenever the migration is scheduled. Reverted the probe; tree is clean.

**Comment by Dicklesworthstone** [comment]
Status check (2026-05-01): tracking issue still applicable, leaving open.

- `Cargo.toml` is still pinned to `russh = "0.46"` / `russh-keys = "0.46"`.
- The deliberate skip is in commit `9af126b chore(deps): bump cargo group (partial: skip rand 0.10 and russh 0.60)` — i.e. the dependency-bump tooling explicitly excluded `russh 0.60` (and `rand 0.10`) from the group bump.
- Mitigation in place: `83acf8e docs(security): warn against KEYBOARD_INTERACTIVE on russh 0.46 (GHSA-f5v4-2wr6-hqmg)` documents the workaround.

Will revisit once `russh 0.60`'s `pkcs8`/`ed25519-dalek` pre-release conflict resolves upstream.

**Comment by Dicklesworthstone** [comment]
## Probe 2026-05-02: upstream pkcs8/ed25519-dalek conflict is RESOLVED

Reproduced today on a clean throwaway crate:

```toml
russh = { version = "0.60", features = ["async-trait"] }
russh-keys = "0.49"
```

`cargo check` now resolves the dependency graph and compiles cleanly:

```
Adding ed25519-dalek v3.0.0-pre.6
Adding pkcs8 v0.11.0-rc.11
Adding rsa v0.10.0-rc.16
...
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 30s
```

The exact failure shape from the issue body (E0277/E0308 inside `ed25519-dalek` against `pkcs8::Error::KeyMalformed`) no longer reproduces. Path is open to actually do the migration.

## Workspace probe (charmed-wish)

Bumping `russh = "0.60"` / `russh-keys = "0.49"` in the workspace `Cargo.toml` reveals that the migration is **larger than the README scope sketch** in this issue. The full delta:

1. **`MethodSet` redesign** — the bitflag-style associated constants (`MethodSet::PUBLICKEY`, `::PASSWORD`, `::KEYBOARD_INTERACTIVE`, `::HOSTBASED`, `::NONE`) are gone. The new shape:

   ```rust
   pub struct MethodSet(Vec<MethodKind>);
   pub enum MethodKind { None, Password, PublicKey, HostBased, KeyboardInteractive }
   impl MethodSet {
       pub fn empty() -> Self;
       pub fn all() -> Self;
       pub fn push(&mut self, method: MethodKind);
       pub fn remove(&mut self, method: MethodKind);
   }
   ```

   Every `methods |= MethodSet::PUBLICKEY` becomes `methods.push(MethodKind::PublicKey)`. Touches `crates/wish/src/lib.rs:1170-1216` and the test stubs at L3313/L3336.

2. **`Auth::Reject` gained `partial_success: bool`** — every `Auth::Reject { proceed_with_methods: ... }` literal needs the new field. Touches `handler.rs` in 6 places.

3. **`auth_banner` field removed from `russh::server::Config`** — the new server-side banner path is the trait method `Handler::authentication_banner(&mut self) -> impl Future<Output = Result<Option<String>, Self::Error>> + Send`. We currently set `config.auth_banner` once at construction; need to lift it onto the handler.

4. **`russh_keys::key::PublicKey` is private; use `russh_keys::PublicKey`** (re-export of `ssh_key::PublicKey`). API surface change: `key.name()` → `key.algorithm().as_str()`, `key.public_key_bytes()` → `key.to_bytes()?` (returns `Result<Vec<u8>, _>`). Touches `handler.rs:166`, `:255`, `:266`, `:286`, `:291`.

5. **`KeyPair` removed; use `ssh_key::PrivateKey`** for `Config::keys: Vec<PrivateKey>`. `KeyPair::generate_ed25519()` → `ssh_key::PrivateKey::random(&mut russh_keys::key::safe_rng(), ssh_key::Algorithm::Ed25519)?`. The `try_from(&private_key)` adapter calls in `lib.rs:1225/1231` collapse to passing `private_key` directly.

6. **`SshId::Standard` now takes `Cow<'static, str>`** — already in the issue body; one-liner.

7. **`Handler` trait moved from boxed-future async-trait to native AFIT** — even with `features = ["async-trait"]`, the trait body uses `fn x(&mut self, ...) -> impl Future<Output = ...> + Send` syntax that the `#[async_trait]` macro doesn't transform cleanly. Concretely: 14 of our `async fn` impl methods get `E0195: lifetime parameters do not match` because the trait now declares e.g. `fn auth_keyboard_interactive<'a>(&'a mut self, ..., response: Option<Response<'a>>)` and our `'async_trait`-shaped impl can't satisfy it.

   The clean fix is to drop `#[async_trait]` from the impl and convert each method to `fn x(...) -> impl Future<Output = ...> + Send { async move { ... } }`. That's mechanical but touches every Handler method (~14) and is the right long-term shape regardless.

## Total compiler error count

`cargo check -p charmed-wish` after the dep bump: **44 errors across `lib.rs` and `handler.rs`**, in the categories above. All known causes, all mechanical, no architectural surprises.

## Recommended split

Rather than a single big-bang PR, this should be a small chain:

1. **prep:** introduce `Handler::authentication_banner` plumbing on the wish side, still on russh 0.46 (no-op).
2. **bump:** dep bump + MethodSet/MethodKind switch + Auth::Reject field + SshId::Standard Cow + key API rename. Keeps `#[async_trait]`.
3. **AFIT:** drop `async_trait` on the russh Handler impl, rewrite the 14 methods as native AFIT. Optional: keep `async_trait` elsewhere unchanged.
4. **README/docs:** revert the `KEYBOARD_INTERACTIVE` warning added in 83acf8e — once we're past 0.49 the GHSA-f5v4-2wr6-hqmg DoS is fixed.

Each step is independently testable and reviewable.

## Status

Leaving this issue **open** as the migration tracker — the upstream block is gone but the on-our-side work hasn't landed. Closing once the AFIT step (step 3) merges and the security warning is dropped.

**Comment by Dicklesworthstone** [comment]
## Status update — 2026-05-02

**Upstream blocker is resolved.** Probe build with `russh = \"0.60\"` + `russh-keys = \"0.49\"` now resolves cleanly: `pkcs8 v0.11.0-rc.11`, `ed25519-dalek v3.0.0-pre.6`, and `internal-russh-forked-ssh-key v0.6.18+upstream-0.6.7` all compile together. `cargo check` succeeds on a minimal probe crate.

**Migration scope is materially larger than the original migration plan in this issue, though.** Things the original list missed (verified by attempting the upgrade in `crates/wish` and rolling it back):

1. **`MethodSet` was completely redesigned.** It is no longer a `bitflags`-style struct — it's now `pub struct MethodSet(Vec<MethodKind>)` with `push(MethodKind::PublicKey)` instead of `|= MethodSet::PUBLICKEY`. Every constant (`MethodSet::NONE`, `PASSWORD`, `PUBLICKEY`, `KEYBOARD_INTERACTIVE`, `HOSTBASED`) is gone. Affects `create_russh_config` and `method_set_from` in handler.rs.

2. **`russh::server::Handler` switched to native AFIT.** Even with `features = [\"async-trait\"]` enabled on russh, our `#[async_trait]` impl produces `error[E0195]: lifetime parameters or bounds on method ... do not match the trait declaration` for every overridden method (`auth_password`, `auth_publickey`, `auth_keyboard_interactive`, `channel_close`, `channel_eof`, `channel_open_session`, `data`, `env_request`, `exec_request`, `pty_request`, `shell_request`, `subsystem_request`, `window_change_request`, `auth_none`). The `async-trait` feature appears to be only for *internal* russh code paths, not for downstream Handler impls. The whole `WishHandler` impl needs to be rewritten using native `async fn` in trait methods.

3. **`Auth::Reject` requires a `partial_success` field.** The trait now wants `Auth::Reject { proceed_with_methods, partial_success }`. `map_auth_result` needs updating.

4. **`config.auth_banner` was renamed.** New name lives among 11 other fields; no `auth_banner` on `russh::server::Config` anymore.

5. **`russh_keys::safe_rng` doesn't exist as a free function** at that path — needs to be located in the new keys module structure.

6. **There are now two `PrivateKey` types**: `russh::keys::PrivateKey` (re-export of `internal_russh_forked_ssh_key::PrivateKey`) and `ssh_key::PrivateKey`. `config.keys: Vec<russh::keys::PrivateKey>`, so we cannot push an `ssh_key::PrivateKey` directly — need to convert via the russh re-export.

7. **`russh_keys::PublicKey::name()` is gone.** `key.algorithm().as_str()` is correct, but the returned string slice is owned by a temporary `Algorithm` and needs `let alg = key.algorithm(); let key_name = alg.as_str();` to outlive the match.

8. **`russh_keys::PublicKeyBase64` import is dead.** Trait no longer exists / is unused; remove.

This is a real, security-driven migration (DoS in `KEYBOARD_INTERACTIVE`, GHSA-f5v4-2wr6-hqmg) but it deserves a focused PR rather than being bundled into a triage sweep — the Handler rewrite alone touches every overridden method and needs careful re-testing of the auth state machine, pty flow, exec parsing, and shell sessions. Keeping this issue open as the canonical work item.

**Probe state:** isolated `russh = \"0.60\"` minimal crate compiles cleanly. The README security warning about `KEYBOARD_INTERACTIVE` is already in place (commits `83acf8e` / `01cea50` / `bb7098c`), so the user-facing exposure window is documented.

**Comment by Dicklesworthstone** [comment]
**Probe result: upstream block is cleared.**

`cargo check` against a fresh project with `russh = "0.60"` + `russh-keys = "0.49"` resolves cleanly today against published `pkcs8 0.11.0` — `internal-russh-forked-ssh-key 0.6.18` + `ed25519-dalek 3.0.0-pre.6` line up. The "Manual probe" section's reopen condition is met.

**Migration scope is bigger than the issue body documented.**

I ran the migration against `crates/wish` to gauge actual surface area. The 7 sites in the body (KeyPair → PrivateKey, SshId Cow wrap, key.name/public_key_bytes accessor renames) compile cleanly, but cargo check then surfaces **39 additional errors** from API changes that landed between 0.46 and 0.60 and aren't in the body's migration scope:

- **`russh::server::Handler` trait** — every impl method (`auth_publickey`, `auth_password`, `auth_none`, `auth_keyboard_interactive`, `channel_open_session`, `pty_request`, `shell_request`, `exec_request`, `env_request`, `subsystem_request`, `window_change_request`, `data`, `channel_eof`, `channel_close`) reports E0195 "lifetime parameters or bounds on method ... do not match the trait declaration". Even with `features = ["async-trait"]`, the trait's lifetime bounds shifted in 0.49+. Every Handler method needs a signature update (likely to drop the `'_` elision and accept a longer-lived borrow, or to switch to native AFIT and stop using `#[async_trait]` entirely).
- **`russh::MethodSet`** — `MethodSet::NONE / PASSWORD / PUBLICKEY / KEYBOARD_INTERACTIVE / HOSTBASED` no longer exist as associated constants; the type was redesigned (probably to bitflags-style `MethodSet::PUBLIC_KEY` or `MethodKind::PublicKey` enum + builder). Every callsite that ORs these together needs translation.
- **`russh::server::Auth`** — the `Auth::Reject { proceed_with_methods }` variant is missing the new `partial_success` field. Every Auth construction needs the extra field threaded through.
- **`russh::server::Config::auth_banner`** — field removed in 0.60. `crates/wish/src/lib.rs:1250` sets it. Need to find the new banner mechanism (probably moved to `Handler::message_after_auth` or similar).
- **Minor**: `key.algorithm()` returns a temporary that needs to be bound to a `let`, and at least 2 `mismatched types` errors I didn't dig into.

So the actual migration is closer to "rewrite the russh integration layer" than "swap a few accessor names". The security motivation is unchanged — `keyboard_interactive` auth is still vulnerable on 0.46 — but this is no longer a drive-by upgrade.

I have the partial-migration diff stashed locally (`charmed-rust russh 0.60 partial migration` in the stash) if it would save you time. Recommend either:

1. **Surface area triage first** — port the Handler trait + MethodSet + Auth changes in a separate PR before the upgrade, so the upgrade itself is a tight Cargo.toml + import-path change.
2. **Big-bang upgrade** — accept the multi-day refactor cost in one PR. Fine if the wish API surface is being evolved anyway.
3. **Keep the workaround** — leave the README warning in place and revisit when russh ships a release with smaller delta-from-0.46. (Not recommended; the GHSA exposure is real.)

Holding open as the tracker; reopening for direction.

**Comment by Dicklesworthstone** [comment]
Fixed in 8ae8856 (auto-closed via commit reference).

Full migration shipped — the upstream pkcs8 / ed25519-dalek deadlock cleared as predicted, and once I had the full picture the remaining surface area was tractable. Notes worth pinning for future me:

- **Switched to native AFIT.** russh's Handler trait went to native-AFIT (`fn …() -> impl Future + Send`) with `#[async_trait]` only as an opt-in feature. Mixing the macro on the impl side while the trait is on native AFIT triggers E0195 lifetime mismatches on every method. Dropping the `async-trait` feature on russh AND the `#[async_trait]` attribute on `impl Handler for WishHandler` was the unblock — edition 2024 / Rust 1.85 handles AFIT in trait impls directly.
- **`russh::keys::*` not `russh-keys::*`.** russh now re-exports its key types from `internal-russh-forked-ssh-key`, while standalone `russh-keys` resolves to a different `ssh-key` version. Cargo treats `russh::keys::PrivateKey` and `ssh_key::PrivateKey` as distinct types — surfaced as E0308 at `Config::keys.push(key)`. Dropped both the standalone `russh-keys` and `ssh-key` deps from `crates/wish/Cargo.toml` and went through `russh::keys::*` everywhere.
- **`MethodSet` is now an ordered Vec, not bitflags.** `MethodSet::PUBLICKEY` etc. are gone; use `methods.push(MethodKind::PublicKey)`. `push` is idempotent (existing entries move to the end), preserving the OR semantic the bitflags form had. `methods.contains(MethodSet::FOO)` becomes `methods.contains(&MethodKind::Foo)` (slice deref + reference).
- **`Auth::Reject { partial_success: bool }`.** New required field on the Reject variant for two-factor staging. Wish has no two-factor surface today so we set `false` everywhere; `map_auth_result` is the place to flip if we ever add it.
- **`Config::auth_banner` field is gone.** Banners moved to `Handler::authentication_banner()`. The new impl surfaces `ServerOptions.banner_handler` first (dynamic, per-connection) and falls back to the static `ServerOptions.banner` — same behaviour as the pre-upgrade static-banner path.
- **`Session::channel_success` / `channel_failure` now return `Result`.** Propagated via `?` in 11 sites; wish's `Error::Russh(#[from] russh::Error)` makes that one-character.

The migration plan in the issue body covered ~7 of ~46 errors — the rest emerged once `cargo check` ran through the file. Documented all of them in the commit message for the next time we cross a major russh boundary.

94 lib tests + 28 auth tests + 40 session tests pass; clippy clean with `-D warnings` on the wish crate.

The README warnings about avoiding `with_keyboard_interactive_auth(...)` on internet-facing servers have been removed; the GHSA fix is now in.
